E:/project/SystemVerilog/riscv/src/adder.sv
E:/project/SystemVerilog/riscv/src/alu.sv
E:/project/SystemVerilog/riscv/src/branch_con.sv
E:/project/SystemVerilog/riscv/src/CPU_top.sv
E:/project/SystemVerilog/riscv/src/ctrl_gen.sv
E:/project/SystemVerilog/riscv/src/decoder.sv
E:/project/SystemVerilog/riscv/src/icache.sv
E:/project/SystemVerilog/riscv/src/imm_gen.sv
E:/project/SystemVerilog/riscv/src/memory.sv
E:/project/SystemVerilog/riscv/src/pc.sv
E:/project/SystemVerilog/riscv/src/reg_file.sv
E:/project/SystemVerilog/riscv/src/shifter.sv
E:/project/SystemVerilog/riscv/src/dcache.sv